// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	ReminderList(ctx context.Context, in *ReminderListRequest, opts ...grpc.CallOption) (*ReminderListResponse, error)
	ReminderCreate(ctx context.Context, in *ReminderCreateRequest, opts ...grpc.CallOption) (*ReminderCreateResponse, error)
	ReminderUpdate(ctx context.Context, in *ReminderUpdateRequest, opts ...grpc.CallOption) (*ReminderUpdateResponse, error)
	ReminderRemove(ctx context.Context, in *ReminderRemoveRequest, opts ...grpc.CallOption) (*ReminderRemoveResponse, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) ReminderList(ctx context.Context, in *ReminderListRequest, opts ...grpc.CallOption) (*ReminderListResponse, error) {
	out := new(ReminderListResponse)
	err := c.cc.Invoke(ctx, "/Admin/ReminderList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ReminderCreate(ctx context.Context, in *ReminderCreateRequest, opts ...grpc.CallOption) (*ReminderCreateResponse, error) {
	out := new(ReminderCreateResponse)
	err := c.cc.Invoke(ctx, "/Admin/ReminderCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ReminderUpdate(ctx context.Context, in *ReminderUpdateRequest, opts ...grpc.CallOption) (*ReminderUpdateResponse, error) {
	out := new(ReminderUpdateResponse)
	err := c.cc.Invoke(ctx, "/Admin/ReminderUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ReminderRemove(ctx context.Context, in *ReminderRemoveRequest, opts ...grpc.CallOption) (*ReminderRemoveResponse, error) {
	out := new(ReminderRemoveResponse)
	err := c.cc.Invoke(ctx, "/Admin/ReminderRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	ReminderList(context.Context, *ReminderListRequest) (*ReminderListResponse, error)
	ReminderCreate(context.Context, *ReminderCreateRequest) (*ReminderCreateResponse, error)
	ReminderUpdate(context.Context, *ReminderUpdateRequest) (*ReminderUpdateResponse, error)
	ReminderRemove(context.Context, *ReminderRemoveRequest) (*ReminderRemoveResponse, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) ReminderList(context.Context, *ReminderListRequest) (*ReminderListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReminderList not implemented")
}
func (UnimplementedAdminServer) ReminderCreate(context.Context, *ReminderCreateRequest) (*ReminderCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReminderCreate not implemented")
}
func (UnimplementedAdminServer) ReminderUpdate(context.Context, *ReminderUpdateRequest) (*ReminderUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReminderUpdate not implemented")
}
func (UnimplementedAdminServer) ReminderRemove(context.Context, *ReminderRemoveRequest) (*ReminderRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReminderRemove not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_ReminderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReminderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ReminderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Admin/ReminderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ReminderList(ctx, req.(*ReminderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ReminderCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReminderCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ReminderCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Admin/ReminderCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ReminderCreate(ctx, req.(*ReminderCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ReminderUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReminderUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ReminderUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Admin/ReminderUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ReminderUpdate(ctx, req.(*ReminderUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ReminderRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReminderRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ReminderRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Admin/ReminderRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ReminderRemove(ctx, req.(*ReminderRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReminderList",
			Handler:    _Admin_ReminderList_Handler,
		},
		{
			MethodName: "ReminderCreate",
			Handler:    _Admin_ReminderCreate_Handler,
		},
		{
			MethodName: "ReminderUpdate",
			Handler:    _Admin_ReminderUpdate_Handler,
		},
		{
			MethodName: "ReminderRemove",
			Handler:    _Admin_ReminderRemove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
