services:
  postgres:
    image: postgres
    env_file: .env
    container_name: 'postgresql-container-reminder-manager'
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    restart: always
  redis:
    image: redis
    container_name: 'redis'
    ports:
      - 6379:6379
