// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api.proto

package api

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataClient interface {
	ReminderList(ctx context.Context, in *ReminderListRequest, opts ...grpc.CallOption) (*ReminderListResponse, error)
	ReminderGet(ctx context.Context, in *ReminderGetRequest, opts ...grpc.CallOption) (*ReminderGetResponse, error)
	ReminderCreate(ctx context.Context, in *ReminderCreateRequest, opts ...grpc.CallOption) (*ReminderCreateResponse, error)
	ReminderUpdate(ctx context.Context, in *ReminderUpdateRequest, opts ...grpc.CallOption) (*ReminderUpdateResponse, error)
	ReminderRemove(ctx context.Context, in *ReminderRemoveRequest, opts ...grpc.CallOption) (*ReminderRemoveResponse, error)
}

type dataClient struct {
	cc grpc.ClientConnInterface
}

func NewDataClient(cc grpc.ClientConnInterface) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) ReminderList(ctx context.Context, in *ReminderListRequest, opts ...grpc.CallOption) (*ReminderListResponse, error) {
	out := new(ReminderListResponse)
	err := c.cc.Invoke(ctx, "/Data/ReminderList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) ReminderGet(ctx context.Context, in *ReminderGetRequest, opts ...grpc.CallOption) (*ReminderGetResponse, error) {
	out := new(ReminderGetResponse)
	err := c.cc.Invoke(ctx, "/Data/ReminderGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) ReminderCreate(ctx context.Context, in *ReminderCreateRequest, opts ...grpc.CallOption) (*ReminderCreateResponse, error) {
	out := new(ReminderCreateResponse)
	err := c.cc.Invoke(ctx, "/Data/ReminderCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) ReminderUpdate(ctx context.Context, in *ReminderUpdateRequest, opts ...grpc.CallOption) (*ReminderUpdateResponse, error) {
	out := new(ReminderUpdateResponse)
	err := c.cc.Invoke(ctx, "/Data/ReminderUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) ReminderRemove(ctx context.Context, in *ReminderRemoveRequest, opts ...grpc.CallOption) (*ReminderRemoveResponse, error) {
	out := new(ReminderRemoveResponse)
	err := c.cc.Invoke(ctx, "/Data/ReminderRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServer is the server API for Data service.
// All implementations must embed UnimplementedDataServer
// for forward compatibility
type DataServer interface {
	ReminderList(context.Context, *ReminderListRequest) (*ReminderListResponse, error)
	ReminderGet(context.Context, *ReminderGetRequest) (*ReminderGetResponse, error)
	ReminderCreate(context.Context, *ReminderCreateRequest) (*ReminderCreateResponse, error)
	ReminderUpdate(context.Context, *ReminderUpdateRequest) (*ReminderUpdateResponse, error)
	ReminderRemove(context.Context, *ReminderRemoveRequest) (*ReminderRemoveResponse, error)
	mustEmbedUnimplementedDataServer()
}

// UnimplementedDataServer must be embedded to have forward compatible implementations.
type UnimplementedDataServer struct {
}

func (UnimplementedDataServer) ReminderList(context.Context, *ReminderListRequest) (*ReminderListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReminderList not implemented")
}
func (UnimplementedDataServer) ReminderGet(context.Context, *ReminderGetRequest) (*ReminderGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReminderGet not implemented")
}
func (UnimplementedDataServer) ReminderCreate(context.Context, *ReminderCreateRequest) (*ReminderCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReminderCreate not implemented")
}
func (UnimplementedDataServer) ReminderUpdate(context.Context, *ReminderUpdateRequest) (*ReminderUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReminderUpdate not implemented")
}
func (UnimplementedDataServer) ReminderRemove(context.Context, *ReminderRemoveRequest) (*ReminderRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReminderRemove not implemented")
}
func (UnimplementedDataServer) mustEmbedUnimplementedDataServer() {}

// UnsafeDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServer will
// result in compilation errors.
type UnsafeDataServer interface {
	mustEmbedUnimplementedDataServer()
}

func RegisterDataServer(s grpc.ServiceRegistrar, srv DataServer) {
	s.RegisterService(&Data_ServiceDesc, srv)
}

func _Data_ReminderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReminderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).ReminderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Data/ReminderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).ReminderList(ctx, req.(*ReminderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_ReminderGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReminderGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).ReminderGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Data/ReminderGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).ReminderGet(ctx, req.(*ReminderGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_ReminderCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReminderCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).ReminderCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Data/ReminderCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).ReminderCreate(ctx, req.(*ReminderCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_ReminderUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReminderUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).ReminderUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Data/ReminderUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).ReminderUpdate(ctx, req.(*ReminderUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_ReminderRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReminderRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).ReminderRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Data/ReminderRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).ReminderRemove(ctx, req.(*ReminderRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Data_ServiceDesc is the grpc.ServiceDesc for Data service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Data_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReminderList",
			Handler:    _Data_ReminderList_Handler,
		},
		{
			MethodName: "ReminderGet",
			Handler:    _Data_ReminderGet_Handler,
		},
		{
			MethodName: "ReminderCreate",
			Handler:    _Data_ReminderCreate_Handler,
		},
		{
			MethodName: "ReminderUpdate",
			Handler:    _Data_ReminderUpdate_Handler,
		},
		{
			MethodName: "ReminderRemove",
			Handler:    _Data_ReminderRemove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
